### ISSUE TITLE
Expose quest (chain) meta data

### ISSUE THREAD

**Issue by dan13ram** [quest-chains/dapp#1]
Metadata to be displayed in the UI for a quest chain and quest 👇 
Note: All of the metadata listed below is already exposed by the subgraph.

## Quest chain

- [x] Title
- [x] Description
- [x] Network
- [x] Members
- [x] Creator
- [x] Date of creation
- [x] Number of quests
- [x] Number of players
- [ ] History of edits (with editor)

## Quest

- [x] Title
- [x] Description
- [ ] Creator
- [ ] Date of creation
- [ ] Number of players
- [ ] History of edits (with editor)

**Comment by dan13ram** [comment]
Ref https://github.com/quest-chains/mono-repo/issues/31
